### ISSUE TITLE
Can record creators be stored as contributors with `contributor_type=Creator`?

### ISSUE THREAD

**Issue by jake-nz** [amds-ldeo/ada-db-spec#4]
Is a creator just another type of contributor or is there a fundamental difference?

**Comment by smrgeoinfo** [comment]
DataCite has different fields for 'creators' and 'contributors'.   

- creator: "The main researchers involved working on the data, or the authors of the publication in priority order. May be a corporate/institutional or personal name."
- contributor: "The institution or person responsible for collecting, creating, or otherwise contributing to the developement of the dataset."

You can see that there is some ambiguity... basically a judgment call on the part of whoever is creating the metadata (hopefully in collaboration with the authors).

DataCite also has a hard type for 'publisher': "The name of the entity that holds, archives, publishes prints, distributes, releases, issues, or produces the resource. This property will be used to formulate the citation, so consider the prominence of the role."

here's the DataCite contributorTypes:
 ```
"ContactPerson",
                "DataCollector",
                "DataCurator",
                "DataManager",
                "Distributor",
                "Editor",
                "HostingInstitution",
                "Producer",
                "ProjectLeader",
                "ProjectManager",
                "ProjectMember",
                "RegistrationAgency",
                "RegistrationAuthority",
                "RelatedPerson",
                "Researcher",
                "ResearchGroup",
                "RightsHolder",
                "Sponsor",
                "Supervisor",
                "WorkPackageLeader",
                "Other"
```

**Comment by jake-nz** [comment]
Thanks @smrgeoinfo!
Closing this as it seems simplest to match how DataCite do it
